# Generated by Django 3.1 on 2020-09-01 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200901_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 9, 28, 43, 187580, tzinfo=utc)),
        ),
    ]
